imperionet/urls.py
from django.contrib import admin
from django.urls import path, include
from vendas import views
from django.conf import settings
from django.conf.urls.static import static
from vendas.views import CreateDados, Ver_Dados, Ver_Formulario, Loja, About, Produtos, Status, UpdateStatus, Plano1, VerOcorrencia, DeletarOcorrencia

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    path("", include("pages.urls", namespace="pages")),
    path('dados/', CreateDados.as_view(), name='dados'),
    path('perfil/', Ver_Dados.as_view(), name='ver_dados'),
    path('contato/', Ver_Formulario.as_view(), name='ver_formulario'),
    path('loja/', Loja.as_view(), name='loja'),
    path('about/', About.as_view(), name='about'),
    path('produtos/', Produtos.as_view(), name='produtos'),
    path('produtos/item/', Plano1.as_view(), name='plano1'),
    path('status/', Status.as_view(), name='status'),
    path('gerenciar/<int:pk>/', UpdateStatus.as_view(), name='update_status'),
    path('ocorrencias/', VerOcorrencia.as_view(), name='ocorrencias'),
    path('ocorrencias/concluir/<int:pk>', DeletarOcorrencia.as_view(), name='concluir-ocorrencia'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),

]

pages/models.py
from django.db import models

# Create your models here.

vendas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.

class plano_internet(models.Model):
    nome_plano = models.CharField(max_length=60)
    data_assinatura = models.CharField(verbose_name='Data Plano:', max_length=60, blank=True, null=True)
    
    def __str__(self):
            return "{}".format(self.nome_plano)

class bairro_internet(models.Model):
    bairro_net = models.CharField(max_length=60)
    nome_rua = models.CharField(verbose_name='Rua:', max_length=60, blank=True, null=True)

    def __str__(self):
            return "{}".format(self.bairro_net)


class Dados(models.Model):
    nome = models.CharField(verbose_name='Nome Completo:', max_length=60, blank=True)
    plano = models.ForeignKey(plano_internet, max_length=60, null=True, on_delete=models.PROTECT)
    endereço = models.ForeignKey(bairro_internet, max_length=60, null=True, on_delete=models.PROTECT)
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)


class Estado(models.Model):
    status = models.CharField(verbose_name='Status:', max_length=60, blank=True)
    motivo = models.CharField(verbose_name='Motivo:', max_length=60, blank=True)
    data_atual = models.CharField(verbose_name='Data Atual:', max_length=60, blank=True)
    afetado = models.CharField(verbose_name='Locais Afetados:', max_length=60, blank=True)
    retorno = models.CharField(verbose_name='Retorno:', max_length=60, blank=True)


class Loja(models.Model):
    nome_objeto = models.CharField(verbose_name='Nome:', max_length=60, blank=True)
    descricao = models.CharField(verbose_name='Descrição:', max_length=250, blank=True)
    preço = models.CharField(verbose_name='Preço:', max_length=60, blank=True)
    disponibilidade = models.CharField(verbose_name='Disponibilidade:', max_length=60, blank=True)
    foto = models.ImageField(verbose_name='Foto', upload_to='media/', default='/static/no_image.png')


class Ocorrencia(models.Model):
    nome_ocorrencia = models.CharField(verbose_name='Nome da Ocorrencia:', max_length=100, blank=True)
    motivo_ocorrencia = models.CharField(verbose_name='Motivo da Ocorrencia:', max_length=200, blank=True)
    local_ocorrencia = models.CharField(verbose_name='Local da Ocorrencia:', max_length=60, blank=True)
    nome_cliente = models.CharField(verbose_name='Nome do Cliente:', max_length=60, blank=True)

    def __str__(self):
            return "{}".format(self.nome_ocorrencia)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

vendas/views.py
from django.shortcuts import render
from vendas.models import Dados, Estado, Loja, Ocorrencia
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User
import PIL


################################################### TEMPLATE VIEW ##################
class VerOcorrencia(ListView):
    model = Ocorrencia
    template_name = 'ocorrencia.html'


class DeletarOcorrencia(DeleteView):
    model = Ocorrencia
    template_name = 'ocorrencia-delete.html'
    success_url = ('/')


class Produtos(TemplateView):
    template_name = 'produtos_loja.html'


class Loja(TemplateView):
    template_name = 'produtos.html'


class About(TemplateView):
    template_name = 'about.html'


class Plano1(TemplateView):
    template_name = 'itens1.html'


############################################### CREATE VIEW ####################
class CreateDados(CreateView):
    model = Dados
    fields = ['nome', 'plano', 'endereço']
    template_name = 'dados.html'
    success_url = ('/')

    def form_valid(self, form):

        form.instance.usuario = self.request.user

        url = super().form_valid(form)

        return url

################################################## LIST VIEW #########################


class Ver_Dados(ListView):
    model = Dados
    template_name = 'perfil.html'

    def get_queryset(self):
        self.object_list = Dados.objects.filter(usuario=self.request.user)
        return self.object_list


class Ver_Formulario(ListView):
    model = Dados
    template_name = 'formulario.html'


class Status(ListView):
    model = Estado
    template_name = 'status_rede.html'


############################################### UPDATEVIEW ################################

class UpdateStatus(UpdateView):
    model = Estado
    fields = ['status', 'motivo', 'data_atual', 'afetado', 'retorno']
    template_name = 'rede.html'
    success_url = ('/')

templates/about.html
<!DOCTYPE html>
<html lang="pt-BR">
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>Loja Imperio</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-sm py-3 border-bottom navbar-light">
        <div class="container">
            <a href="{% url 'pages:home' %}" class="navbar-brand">
                <span class="font-weight-bold h3">IMPERIO NETWORKS</span>
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="/loja" class="nav-link lead mr-4 font-weight-bold">Voltar</a>
                    </li>
                    <li class="nav-item">
                        <a href="/produtos" class="nav-link lead mr-4 font-weight-bold">Produtos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

</body>

</html>

<div class="container my-3">
    <h1 class="font-weight-bold">Sobre nós</h1>
    <p>
        Aqui, e possivel fazer encomenda de diversos produtos, e contratar planos de internet
        Sendo assim criamos esta loja para melhorar e inovar cada vez mais o nosso atendimento
        E proporcionar cada vez mais, a melhor esperiencia de Atendimento, encomendas de produtos
        E dentre outros! E quaquer dúvida, entre em CONTATO! nos estamos prontos para te ajudar!!
    </p>
    <p>
        Nosso site, também preza pela segurança de nossos clientes em todos os nossos serviços <br>
        Sendo assim as compras de produtos e assinatura de planos de internet, sao feitas pelo nosso <br>
        Canal de comunicação pelo <strong>Whatsapp</strong>! E todas as informações passadas aqui por Você <br>
        São pessoais totalmente CRIPTOGRAFADAS, Boas Compras!
    </p>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">IMPERIO NETWORKS</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <title>IMPERIO NETWORKS</title>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">IMPERIO NETWORKS</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/status">Internet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/loja">Loja</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/perfil">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>


    {% if user.is_authenticated %}

        <div id="carouselSite" class="carousel slide" data-ride="carousel">

            <ol class="carousel-indicators">
                <li data-target="#carouselSite" data-slide-to="0" class="active"></li>
                <li data-target="#carouselSite" data-slide-to="1" class="active"></li>
                <li data-target="#carouselSite" data-slide-to="2" class="active"></li>
            </ol>

            <div class="carousel-inner">

                <div class="carousel-item active">

                    <img src="{% static 'midia/baner10.png' %}" alt="ft" class="img-fluid d-block">

                </div>

                <div class="carousel-item">

                    <img src="{% static 'midia/baner20.png' %}" alt="ft" class="img-fluid d-block">

                </div>

                <div class="carousel-item">

                    <img src="{% static 'midia/baner30.png' %}" alt="ft" class="img-fluid d-block">

                </div>


            </div>
            
            <a href="#carouselSite" class="carousel-control-prev" role="button" data-slide="prev">

                <span class="carousel-control-prev-icon"></span>
                <span class="sr-only">Anterior</span>

            </a>
            
            <a href="#carouselSite" class="carousel-control-next" id="carouselSite" role="button" data-slide="next">

                <span class="carousel-control-next-icon"></span>
                <span class="sr-only">Proximo</span>

            </a>

        </div>

    {% endif %}
    <h1></h1>


    <br><br><br>

{% if user.is_authenticated %}
    <h2 style="padding: 10px;">Ola {{ user }} Bem-Vindo! Para melhorar nosso atendimento a Você, <br> Nos informe seus <a href="/dados" style="text-decoration: none;
        color: black;">Dados aqui!</a></h2> <a href="/dados" style="display: inline-block;"><button type="button" class="btn btn-primary" style="margin: 10px; size: 30px;">Adicionar seus Dados!</button></a>
    <br><br>
    <h2 style="padding: 10px;">Nosso Objetivo</h2><br>
    <strong>
    <p style="font-size: 20px; text-align: justify; padding: 10px;">Nós da IMPERIO prezamos pela prestatividade <br>
    Com os clientes! Através serviços e planos <br>
    Com Acessibilidade a todos os publicos!, Sendo assim <br>
    Com este Site procuramos a maior comodidade e facilidade <br>
    Aos nossos clientes em relação a: Status da Rede, Realizar Compras <br>
    Solicitar serviços E etc...., Nos ficamos felizes com sua Visita!</p></strong>
    <br>
    <h2 style="padding: 10px;">Nossa Localização</h2><br>
    <p style="font-size: 20px; text-align: justify; padding: 10px;">
        Av. Washington Luís Nº649, Simões Filho-BA
        <a href="https://www.google.com.br/maps/place/Av.+Washington+Lu%C3%ADs,+649+-+Parque+Continental,+Sim%C3%B5es+Filho+-+BA,+43700-000/@-12.7820833,-38.3977668,17z/data=!3m1!4b1!4m5!3m4!1s0x7166b5987618b01:0xd6e7d6c649b67139!8m2!3d-12.7820833!4d-38.3955781" target="_blank"><button type="button" class="btn btn-success">Google Maps</button></a>
    </p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3890.9449927463106!2d-38.39548157630827!3d-12.78208253248196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7166b5987618b01%3A0xd6e7d6c649b67139!2sAv.%20Washington%20Lu%C3%ADs%2C%20649%20-%20Parque%20Continental%2C%20Sim%C3%B5es%20Filho%20-%20BA%2C%2043700-000!5e0!3m2!1spt-BR!2sbr!4v1622661757970!5m2!1spt-BR!2sbr" width="600" height="450" style="border:0; padding: 10px;" allowfullscreen="" loading="lazy"></iframe>
    <hr>
    <br><br>
    <h1>ENTRE EM CONTATO!</h1>
</body>


<br><br><br><br><br>
<footer>
        <style>
            footer{
                background: rgb(22,142,191);
                background: linear-gradient(90deg, rgba(22,142,191,1) 0%, rgba(7,178,243,1) 0%, rgba(41,3,255,1) 0%, rgba(27,173,228,1) 0%, rgba(3,104,255,1) 39%, rgba(3,46,255,1) 83%, rgba(3,50,255,1) 100%);
                color: white;
                padding: 10px;
                text-align: left;
                font-size: 20px;
                }
                a{
                text-decoration: none;
                color: white;}
                #seila1{
                    text-align: center;
                }
        </style>

        <br>
        <h1><strong>Entre em contato Conosco!</strong></h1><br>
        <ul style="display: inline-block;">   
            <strong>CONTATO</strong>                                                                                                                                                          
                <li><a href="/contato"><strong>Entre em contato conosco!</strong><br></a></li>                                                             
                <li><a href="/contato"><strong>Entre com a administração</strong><br></a></li>
                <li><a href="/contato"><strong>Tire suas dúvidas</strong><br></a></li>
                <li><a href="/contato"><strong>Faça uma sugestão</strong><br></a></li>
        </ul>


        
        <ul style="display: inline-block;"> 
            <strong>SOBRE NOS!</strong>                                                                                                                                                        
                <li><a href="#"" target="_blank"><strong>Nossa história</strong><br></a></li>                                                             
                <li><a href="#"" target="_blank"><strong>Nossa localização</strong><br></a></li>
                <li><a href="#"" target="_blank"><strong>Nossa equipe</strong><br></a></li>
                <li><a href="#"" target="_blank"><strong>Nossos eventos</strong><br></a></li>
        </ul>





        <ul style="display: inline-block;"> 
            <strong>REDES SOCIAIS</strong>                                                                                                                                                        
                <li><a href="#"><strong>Facebook</strong><br></a></li>                                                             
                <li><a href="http://wa.me/557191149124" target="_blank"><strong>WhatsApp</strong><br></a></li>
                <li><a href="#"><strong>Instagran</strong><br></a></li>
                <li><a href="#"><strong>Twitter</strong><br></a></li>
        </ul>

        ____________________
        <strong style="display: inline-block; font-size: 30px;">IMPERIO NETWORKS</strong>
        <br><br>
    </footer>

{% else %}
    <style>
        body{
            background: rgb(22,142,191);
            background: linear-gradient(90deg, rgba(22,142,191,1) 0%, rgba(7,178,243,1) 0%, rgba(41,3,255,1) 0%, rgba(27,173,228,1) 0%, rgba(3,104,255,1) 39%, rgba(3,46,255,1) 83%, rgba(3,50,255,1) 100%);
        }
        main{
            background-color: white;
            width: 700px;
            heigth: 600px;
            margin: auto;
            padding: 10px;
            box-shadow: 6px 6px 10px black;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            font-weight: bolder;
            font-size: 25px;
            border-radius: 15px;
        }
    </style>
        <div class="card" style="width: 30rem; text-align: center; margin: auto;">
            <img src="{% static 'login.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" style="text-align: center;">Login | Cadastro</h5>
              <p class="card-text"><strong>Por aqui você cria um novo Cadastro ou faz o seu Login <br> E então poderá desfrutar de nossos serviços!</strong></p>
            </div>
            <ul class="list-group list-group-flush">
            </ul>
            <div class="card-body">
              <a href="/accounts/login/" type="button" class="btn btn-primary" style="margin-right: 10px;">Login</a>
              <a href="/accounts/signup/" type="button" class="btn btn-primary">Cadastro</a>
            </div>
          </div>
    <br><br>
{% endif %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

templates/itens1.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-BR">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Loja Imperio</title>
    <style>
        main{
            background-color: white;
            width: 700px;
            heigth: 600px;
            padding: 10px;
            font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
            font-weight: bolder;
            font-size: 25px;
            display: inline-block;
        }
        #dv2{
            display: inline-block;
            font-family: Arial, Helvetica, sans-serif;
            font-weight: bold;
            margin-left: 70px;
            font-size: 20px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-sm py-3 border-bottom navbar-light">
        <div class="container">
            <a href="{% url 'pages:home' %}" class="navbar-brand">
                <span class="font-weight-bold h3">IMPERIO NETWORKS</span>
            </a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="/produtos" class="nav-link lead mr-4 font-weight-bold">Voltar</a>
                    </li>
                    <li class="nav-item">
                        <a href="/about" class="nav-link lead mr-4 font-weight-bold">Sobre a Loja</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
        <br>
        <h1 class="font-weight-bold" style="padding-left: 70px;">Finalização do Pedido!</h1> 
        <br><br>
        <div id="dv2">
            <br>
            <p>
                AVISO: Para a sua Segurança, a ação de compras de itens ou assinatura de planos NÃO é feito aqui pelo site! <br> e SIM pelo WhatsApp da IMPERIO NETWORKS!
                Lá você entrará em contato com um dos nossos Atendentes, e poderá contratar planos de internet, fazer encomendas e Muito Mais!
                <br><br>
                <strong><h2 style="text-align: center; display: inline-block; margin-left: 10px;">A IMPERIO AGRADECE SEU PEDIDO!</h2></strong> <div class="spinner-border" role="status" style="display: inline-block;"><span class="visually-hidden"></span></div>
                <br><br>
                <div>
                    <a href="http://wa.me/557191149124" style="font-family: Arial, Helvetica, sans-serif; margin: 10px;" target="__blank"><button type="button" class="btn btn-outline-success">Finalizar Pedido</button></a>
                    <a href="/" style="font-family: Arial, Helvetica, sans-serif;"><button type="button" class="btn btn-outline-danger">Cancelar Compra</button></a>
                </div>
            </p>
        </div>
        <hr>
</body>
</html>